<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\PoliceMember;
use Illuminate\Database\Seeder;

class PoliceMemberSeeder extends Seeder
{
    public function run(): void
    {
        if (PoliceMember::query()->exists()) {
            return;
        }

        foreach ($this->members() as $member) {
            PoliceMember::query()->create($member);
        }
    }

    /**
     * @return list<array<string, mixed>>
     */
    private function members(): array
    {
        return [
            [
                'badge_number' => '101',
                'name' => 'مازن محمد',
                'shoulder_rank' => 'لواء',
                'rank' => 'interior_minister',
                'section' => 'ministry_leadership',
                'status' => 'active',
                'position' => 'وزير الداخلية',
                'discord_username' => 'mazen_mohamed2',
                'discord_id' => '1372247046404440084',
                'points_exempt' => true,
                'joined_at' => '2026-06-29',
                'last_promotion_date' => '2026-06-29',
            ],
            [
                'badge_number' => '102',
                'name' => 'رامز محمد',
                'shoulder_rank' => 'لواء',
                'rank' => 'deputy_interior_minister',
                'section' => 'ministry_leadership',
                'status' => 'active',
                'position' => 'نائب وزير الداخلية',
                'discord_username' => 'g.55',
                'discord_id' => '822036947610370070',
                'points_exempt' => true,
                'joined_at' => '2026-06-29',
                'last_promotion_date' => '2026-06-29',
            ],
            [
                'badge_number' => '103',
                'name' => 'ماكس رولينز',
                'shoulder_rank' => 'عميد',
                'rank' => 'first_assistant_interior_minister',
                'section' => 'ministry_leadership',
                'status' => 'active',
                'position' => 'مساعد أول وزير الداخلية',
                'discord_username' => 'mx2_',
                'discord_id' => '710483755927863318',
                'points_exempt' => true,
                'joined_at' => '2026-06-29',
                'last_promotion_date' => '2026-06-29',
            ],
            [
                'badge_number' => '104',
                'name' => 'محمد مصطفى',
                'shoulder_rank' => 'عميد',
                'rank' => 'first_assistant_interior_minister',
                'section' => 'ministry_leadership',
                'status' => 'active',
                'position' => 'مساعد أول وزير الداخلية',
                'discord_username' => 'muhamdmustaffa',
                'discord_id' => '853096774595772417',
                'points_exempt' => true,
            ],
            [
                'badge_number' => '201',
                'name' => 'ماكس ريدفيلد',
                'shoulder_rank' => 'عقيد',
                'rank' => 'colonel',
                'section' => 'executive_leadership',
                'status' => 'active',
                'discord_username' => 'best',
                'discord_id' => '796038620930375750',
                'points_exempt' => true,
                'joined_at' => '2026-06-29',
                'last_promotion_date' => '2026-06-29',
            ],
            [
                'badge_number' => '202',
                'name' => 'حمد علوش',
                'shoulder_rank' => 'مقدم',
                'rank' => 'lieutenant_colonel',
                'section' => 'executive_leadership',
                'status' => 'active',
                'position' => 'رئيس قطاع الأمن العام',
                'discord_username' => 'kreek_1',
                'discord_id' => '1014825317782802434',
                'joined_at' => '2026-06-30',
                'last_promotion_date' => '2026-06-30',
            ],
            [
                'badge_number' => '203',
                'name' => 'محمد العجرودي',
                'shoulder_rank' => 'مقدم',
                'rank' => 'lieutenant_colonel',
                'section' => 'executive_leadership',
                'status' => 'active',
                'position' => 'رئيس وحدة المباحث',
                'discord_username' => 'mohhamedmano',
                'discord_id' => '379061585794039808',
                'joined_at' => '2026-06-30',
                'last_promotion_date' => '2026-06-30',
            ],
            [
                'badge_number' => '204',
                'name' => 'قاظم أباظة',
                'shoulder_rank' => 'مقدم',
                'rank' => 'lieutenant_colonel',
                'section' => 'executive_leadership',
                'status' => 'active',
                'position' => 'رئيس الأمن المركزي',
                'discord_username' => 'kthugfamilia',
                'discord_id' => '1079755748126507118',
                'joined_at' => '2026-06-29',
                'last_promotion_date' => '2026-06-29',
            ],
            [
                'badge_number' => '205',
                'name' => 'كريم ويليم',
                'shoulder_rank' => 'مقدم',
                'rank' => 'lieutenant_colonel',
                'section' => 'executive_leadership',
                'status' => 'active',
                'position' => 'رئيس قطاع الأمن الوطني',
                'discord_username' => 'af8any_99_84524',
                'discord_id' => '1437950161761468519',
                'joined_at' => '2026-06-29',
                'last_promotion_date' => '2026-06-29',
            ],
            [
                'badge_number' => '206',
                'name' => 'عبدالرحمن أحمد',
                'shoulder_rank' => 'رائد',
                'rank' => 'major',
                'section' => 'executive_leadership',
                'status' => 'active',
                'position' => 'رئيس الاكاديمية',
                'discord_username' => 'mostafa06775',
                'discord_id' => '669369786094059551',
                'joined_at' => '2026-06-29',
                'last_promotion_date' => '2026-06-29',
            ],
            [
                'badge_number' => '207',
                'name' => 'نيرة مجدي',
                'shoulder_rank' => 'رائد',
                'rank' => 'major',
                'section' => 'executive_leadership',
                'status' => 'active',
                'position' => 'نائب رئيس الاكاديمية',
                'discord_username' => '_naira',
                'discord_id' => '578489617322475551',
                'joined_at' => '2026-06-29',
                'last_promotion_date' => '2026-06-29',
            ],
            [
                'badge_number' => '208',
                'name' => 'أحمد الكاشف',
                'shoulder_rank' => 'رائد',
                'rank' => 'major',
                'section' => 'executive_leadership',
                'status' => 'active',
                'position' => 'نائب رئيس وحدة المباحث',
                'discord_username' => 'ahmedatef0802',
                'discord_id' => '1441155961015505028',
                'joined_at' => '2026-06-29',
                'last_promotion_date' => '2026-06-29',
            ],
            [
                'badge_number' => '301',
                'name' => 'إدوارد ووكر',
                'shoulder_rank' => 'ملازم أول',
                'rank' => 'first_lieutenant',
                'section' => 'officers',
                'status' => 'active',
                'discord_username' => 'peshoymena',
                'discord_id' => '1475977767773278380',
                'joined_at' => '2026-06-29',
                'last_promotion_date' => '2026-06-29',
            ],
            [
                'badge_number' => '302',
                'name' => 'علي المصري',
                'shoulder_rank' => 'ملازم',
                'rank' => 'lieutenant',
                'section' => 'officers',
                'status' => 'active',
                'discord_username' => 'hassan3li7777',
                'discord_id' => '1444985572727849012',
                'joined_at' => '2026-06-30',
                'last_promotion_date' => '2026-06-30',
            ],
            [
                'badge_number' => '401',
                'name' => 'شحاتة السيد',
                'shoulder_rank' => 'أمين شرطة',
                'rank' => 'police_secretary',
                'section' => 'secretaries',
                'status' => 'active',
                'discord_username' => 'a7medsoltan',
                'discord_id' => '1056217051351494686',
                'joined_at' => '2026-06-29',
                'last_promotion_date' => '2026-06-29',
            ],
            [
                'badge_number' => '402',
                'name' => 'يوسف صقر',
                'shoulder_rank' => 'أمين شرطة',
                'rank' => 'police_secretary',
                'section' => 'secretaries',
                'status' => 'active',
                'discord_username' => 'youssefali0025',
                'discord_id' => '1438324695714762834',
                'joined_at' => '2026-06-29',
                'last_promotion_date' => '2026-06-29',
            ],
            [
                'badge_number' => '403',
                'name' => 'سليم الرفاعي',
                'shoulder_rank' => 'أمين شرطة',
                'rank' => 'police_secretary',
                'section' => 'secretaries',
                'status' => 'active',
                'discord_username' => 'ahmedsameh4473',
                'discord_id' => '891804170024288287',
                'joined_at' => '2026-06-29',
                'last_promotion_date' => '2026-06-29',
            ],
            [
                'badge_number' => '460',
                'name' => 'هاني الباشا',
                'shoulder_rank' => 'رقيب',
                'rank' => 'sergeant',
                'section' => 'sergeants',
                'status' => 'active',
                'discord_username' => 'tofa7a318',
                'discord_id' => '1351942910316118148',
            ],
            [
                'badge_number' => '461',
                'name' => 'حمدي أبو شديد',
                'shoulder_rank' => 'رقيب',
                'rank' => 'sergeant',
                'section' => 'sergeants',
                'status' => 'active',
                'discord_username' => 'v11ix',
                'discord_id' => '1081343747448643586',
            ],
        ];
    }
}
